apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    {{- include "runtime-sensor.labels" . | nindent 4 }}
    control-plane: runtime-sensor
  name: {{ template "runtime-sensor.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      {{- include "runtime-sensor.selectorLabels" . | nindent 6 }}
      control-plane: runtime-sensor
  template:
    metadata:
      annotations:
        snyk/runtime-sensor: "true"
      labels:
        {{- include "runtime-sensor.selectorLabels" . | nindent 8 }}
        {{- include "runtime-sensor.podLabels" . | nindent 8 }}
        control-plane: runtime-sensor
    spec:
      # This toleration makes sure we run on any node, regardless of taints
      tolerations:
        - operator: Exists
      {{- if and .Values.imagePullSecret }}
      imagePullSecrets:
        - name: "{{ .Values.imagePullSecret }}"
      {{- end }}
      containers:
        - name: runtime-sensor
          imagePullPolicy: IfNotPresent
          {{- if .Values.sensor.extraArgs }}
          args:
            {{- .Values.sensor.extraArgs | toYaml | nindent 12 }}
          {{-  end  }}
          {{- if and .Values.sensor.image.repository .Values.sensor.image.tag }}
          image: "{{ .Values.sensor.image.repository }}:{{ .Values.sensor.image.tag | default .Chart.AppVersion }}"
          {{- else }}
          image: "{{ .Values.sensor.image.repository }}"
          {{- end }}
          resources:
            requests:
              memory: "512Mi"
              cpu: "100m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
          securityContext:
            {{- if .Values.securityContext.privileged }}
            privileged: true
            {{- else }}
            capabilities:
              add:
              {{- with .Values.securityContext.capabilities }}
              {{- toYaml . | nindent 16 }}
              {{- end }}
              drop:
                - ALL
            {{- end }}
          volumeMounts:
            - name: boot-host
              mountPath: /boot.host
              readOnly: true
            - name: sysfs
              mountPath: /sys
              readOnly: true
          env:
            - name: SNYK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: {{ required "A secretName is required! Please provide a value" .Values.secretName }}
                  key: "snykToken"
            - name: CLUSTER_NAME
              value: "{{ .Values.clusterName }}"
            - name: SNYK_GROUP_ID
              value: "{{ .Values.snykGroupId }}"
          envFrom:
          - configMapRef:
              name: env-config-map
              optional: true
      hostPID: true
      serviceAccountName: {{ template "runtime-sensor.serviceAccountName" . }}
      volumes:
        - name: boot-host
          hostPath:
            path: /
        - name: sysfs
          hostPath:
            path: /sys
