{{- if .Values.sensor.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "runtime-sensor.serviceAccountName" . }}
  namespace: snyk-runtime-sensor
  labels:
    {{- include "runtime-sensor.labels" . | nindent 4 }}
  {{- with .Values.sensor.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
